In [33]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report
import pandas as pd

In [34]:
data = {
    "Message": [
        "Win a free iPhone now",
        "Congratulations you have won a lottery",
        "Meeting scheduled at 10 AM tomorrow",
        "Claim your free reward now",
        "Please review the project document",
        "Limited offer buy now",
        "Lunch at 1 PM?",
        "Urgent! Your account has been compromised",
        "Reminder for tomorrow's meeting",
        "Exclusive discount just for you"
    ],
    
    "Label": [
        "spam",
        "spam",
        "ham",
        "spam",
        "ham",
        "spam",
        "ham",
        "spam",
        "ham",
        "spam"
    ]
}

df = pd.DataFrame(data)
df

                                     Message Label
0                      Win a free iPhone now  spam
1     Congratulations you have won a lottery  spam
2        Meeting scheduled at 10 AM tomorrow   ham
3                 Claim your free reward now  spam
4         Please review the project document   ham
5                      Limited offer buy now  spam
6                             Lunch at 1 PM?   ham
7  Urgent! Your account has been compromised  spam
8            Reminder for tomorrow's meeting   ham
9            Exclusive discount just for you  spam

In [35]:
df["Label"] = df["Label"].map({"ham":0,"spam":1})
df

                                     Message  Label
0                      Win a free iPhone now      1
1     Congratulations you have won a lottery      1
2        Meeting scheduled at 10 AM tomorrow      0
3                 Claim your free reward now      1
4         Please review the project document      0
5                      Limited offer buy now      1
6                             Lunch at 1 PM?      0
7  Urgent! Your account has been compromised      1
8            Reminder for tomorrow's meeting      0
9            Exclusive discount just for you      1

In [36]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["Message"])
y = df["Label"]

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [38]:
model = MultinomialNB()
model.fit(X,y)

MultinomialNB()

In [39]:
X_new = ["Get a free new samsung phone"]
X_new_vector = vectorizer.transform(X_new)
prediction = model.predict(X_new_vector)
print(prediction)

[1]

In [40]:
prediction = model.predict(X_test)

In [41]:
print("Accuracy:", accuracy_score(y_test, prediction))

print("\nClassification Report:\n")
print(classification_report(y_test, prediction))

Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2